"""
SQLAlchemy database models for NBA statistics.

Schema:
- Players: Player information (ID, name, team, etc.)
- Teams: Team information
- Matches: Game information (date, home/away teams, etc.)
- Stats: Player stats in matches (points, rebounds, assists, etc.)
- Reports: Analysis reports generated by the system
"""

from sqlalchemy import Column, Integer, String, Float, Date, DateTime, ForeignKey, Text, Boolean
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime
from typing import List, Optional

Base = declarative_base()


class Team(Base):
    """NBA Team information."""
    __tablename__ = "teams"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(50), unique=True, nullable=False)
    abbreviation = Column(String(3), unique=True, nullable=False)
    city = Column(String(50))

    # Relationships
    players = relationship("Player", back_populates="team")
    home_matches = relationship("Match", back_populates="home_team", foreign_keys="Match.home_team_id")
    away_matches = relationship("Match", back_populates="away_team", foreign_keys="Match.away_team_id")

    def __repr__(self):
        return f"<Team {self.name} ({self.abbreviation})>"


class Player(Base):
    """NBA Player information."""
    __tablename__ = "players"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), unique=True, nullable=False)
    team_id = Column(Integer, ForeignKey("teams.id"))
    position = Column(String(10))  # PG, SG, SF, PF, C
    jersey_number = Column(Integer)
    height = Column(Float)  # cm
    weight = Column(Float)  # kg
    birth_date = Column(Date)

    # Relationships
    team = relationship("Team", back_populates="players")
    stats = relationship("Stat", back_populates="player")
    reports = relationship("Report", back_populates="player")

    def __repr__(self):
        return f"<Player {self.name}>"


class Match(Base):
    """NBA Match information."""
    __tablename__ = "matches"

    id = Column(Integer, primary_key=True, index=True)
    date = Column(Date, nullable=False)
    season = Column(Integer)  # 2023, 2024, etc.
    match_type = Column(String(20))  # regular, playoff, finals
    home_team_id = Column(Integer, ForeignKey("teams.id"), nullable=False)
    away_team_id = Column(Integer, ForeignKey("teams.id"), nullable=False)
    home_score = Column(Integer)
    away_score = Column(Integer)

    # Relationships
    home_team = relationship("Team", back_populates="home_matches", foreign_keys=[home_team_id])
    away_team = relationship("Team", back_populates="away_matches", foreign_keys=[away_team_id])
    stats = relationship("Stat", back_populates="match")

    def __repr__(self):
        return f"<Match {self.date}: {self.home_team} vs {self.away_team}>"


class Stat(Base):
    """Player statistics in a match."""
    __tablename__ = "stats"

    id = Column(Integer, primary_key=True, index=True)
    player_id = Column(Integer, ForeignKey("players.id"), nullable=False)
    match_id = Column(Integer, ForeignKey("matches.id"), nullable=False)

    # Scoring
    points = Column(Integer, default=0)
    field_goals_made = Column(Integer, default=0)
    field_goals_attempted = Column(Integer, default=0)
    field_goal_percentage = Column(Float)  # 0-100
    three_pointers_made = Column(Integer, default=0)
    three_pointers_attempted = Column(Integer, default=0)
    three_point_percentage = Column(Float)  # 0-100
    free_throws_made = Column(Integer, default=0)
    free_throws_attempted = Column(Integer, default=0)
    free_throw_percentage = Column(Float)  # 0-100

    # Rebounds
    total_rebounds = Column(Integer, default=0)
    offensive_rebounds = Column(Integer, default=0)
    defensive_rebounds = Column(Integer, default=0)

    # Assists & Ball Handling
    assists = Column(Integer, default=0)
    turnovers = Column(Integer, default=0)
    steals = Column(Integer, default=0)

    # Defense
    blocks = Column(Integer, default=0)
    fouls_personal = Column(Integer, default=0)
    fouls_drawn = Column(Integer, default=0)

    # Efficiency
    plus_minus = Column(Integer)  # +/- rating
    efficiency_rating = Column(Float)  # PER

    minutes_played = Column(Float)  # minutes

    # Relationships
    player = relationship("Player", back_populates="stats")
    match = relationship("Match", back_populates="stats")

    def __repr__(self):
        return f"<Stat {self.player.name} - {self.points}pts>"


class Report(Base):
    """Analysis reports generated by the system."""
    __tablename__ = "reports"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(200), nullable=False)
    player_id = Column(Integer, ForeignKey("players.id"))
    content = Column(Text)
    query_used = Column(String(500))  # SQL query used
    generated_at = Column(DateTime, default=datetime.utcnow)
    report_type = Column(String(50))  # "comparison", "trend", "performance", etc.

    # Relationships
    player = relationship("Player", back_populates="reports")

    def __repr__(self):
        return f"<Report {self.title}>"
